<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Trabalho Empresas Virtuais</title>
    <link rel="stylesheet" href=" reset.css">
    <link rel="stylesheet" href="cyclonegames2.css">
    
</head>
<body>
    <header>
        <img id="logo" src="cyclonegames.png" width="300px" height="300px">
        <h1 class="titulo-principal"> E.E.Softwares </h1>
    </header>


</body>
</html>    
